# Generated by Django 5.2.15 on 2026-06-30 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Производитель')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('diameter', models.FloatField(default=1.75, verbose_name='Диаметр (мм)')),
                ('cost_per_gram', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Себестоимость за грамм')),
                ('stock_grams', models.FloatField(default=0, verbose_name='Остаток (грамм)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('status', models.CharField(choices=[('idle', 'Свободен'), ('printing', 'Печатает'), ('paused', 'Пауза'), ('error', 'Ошибка'), ('maintenance', 'Обслуживание')], default='idle', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('loaded_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printers', to='printerfarm.material', verbose_name='Заправленный материал')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название задания')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('printing', 'Печатается'), ('completed', 'Завершено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('estimated_time_min', models.PositiveIntegerField(default=0, verbose_name='Оценка времени (мин)')),
                ('actual_time_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Факт. время (мин)')),
                ('material_used_grams', models.FloatField(blank=True, null=True, verbose_name='Израсходовано (грамм)')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='printerfarm.material', verbose_name='Материал')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='printerfarm.printer', verbose_name='Принтер')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
    ]
