# Generated by Django 5.2.15 on 2026-07-01 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('printerfarm', '0002_customer_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.customer', verbose_name='Заказчик'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
