# Generated by Django 5.2.15 on 2026-07-02 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printerfarm', '0003_alter_order_customer_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_time_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Время изготовления (мин)'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='order',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='printerfarm.printer', verbose_name='Назначенный принтер'),
        ),
    ]
